config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :restaurants, only: %i[index new show create] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true,
                                     in: 0..5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show; end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container bg-light">
  <h1>Restaurants</h1>
    <div class="row gap-2 border-bottom">
      <% @restaurants.each do |restaurant| %>
        <div class="card col-4" style="width: 20rem;">
          <div class="card-body">
            <img src="https://source.unsplash.com/random/200x200" class="card-img-top" alt="...">
            <h5 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant)%></h5>
            <p class="card-text lead"><i class="fa-solid fa-utensils"></i> <%= restaurant.category %></p>
          </div>
        </div>
      <% end %>
    </div>
  <%= link_to "Add new restaurant", new_restaurant_path, class: 'btn btn-light mt-3' %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h3>Add a Restaurant 🥡</h3>
    <div class="form-floating form-control">
      <%= simple_form_for @restaurant do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category %>
    <div class="form-actions">
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>

<div class="card" style="width: 20rem;">
  <div class="card-body">
    <img src="https://source.unsplash.com/random/food" class="card-img-top" alt="...">
    <h5 class="card-title"><%= @restaurant.name%></h5>
    <p class="card-text lead"><i class="fa-solid fa-utensils"></i> <%= @restaurant.category %></p>
    <p class="card-text"><i class="fa-solid fa-map-pin"></i> <%= @restaurant.address %></p>
    <p class="card-text"><i class="fa-solid fa-phone"></i> <%= @restaurant.phone_number %></p>
  </div>
  <div class="btn btn-light">
    <%= link_to "Back to list", restaurants_path(@restaurant) %>
  </div>
</div>